FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JavaScript file into the container
COPY . .

# Define the command to run the script
CMD [ "node", "Demo.js" ]